package com.phoenixx.core.snapshots;

import com.phoenixx.core.snapshots.data.HTTPObject;

/**
 * @author Junaid Talpur
 * @project Hydra
 * @since 11:56 a.m. [09-05-2023]
 */
public abstract class ISnapshot {

    /**
     * Get the snapshot ID that's associated it with the request in the script itself
     * @return {@link Integer}
     */
    public abstract int getID();

    /**
     * Get the request that was generated by vugen and sent to the application
     * @return {@link HTTPObject}
     */
    public abstract HTTPObject getRequest();

    /**
     * Get the response that was retrieved from the application
     * @return {@link HTTPObject}
     */
    public abstract HTTPObject getResponse();
}
